# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherApp
pod 'RxSwift'
pod 'RxCocoa'
pod 'PureLayout'
pod 'Kingfisher'
pod 'ReachabilitySwift', '~> 4.3.1'
pod 'RxDataSources'

end
